### ISSUE TITLE
PiP mode back to fullscreen crashes Cofi

### ISSUE THREAD

**Issue by Ethanol6** [rozPierog/Cofi#38] opened 2022-01-17 22:21 UTC
Cofi Version: 1.3.3
Android Version: 10
OS: Lineage OS
App Store: F-Droid

### Steps to reproduce
- While a recipe is running, press the "Home" (?) button to force Cofi to enter Picture in Picture mode.
- Try to full screen the app
- PiP window disappears and app quits/crashes silently

**Comment by rozPierog** [comment] 2022-01-18 15:05
Thanks for the report, I can reproduce it on my phone. Guess I wasn't affected by it as I often finish the recipe while in PiP. Will fix it this soon

**Comment by rozPierog** [comment] 2022-01-18 16:16
Turns out that it was compose issue, fixed in https://github.com/rozPierog/Cofi/releases/tag/v1.3.4 with dependency update.

**Closed by rozPierog** 2022-01-18 16:16 UTC

**Comment by Ethanol6** [comment] 2022-01-23 17:14
Got the update on F-Droid. Works perfect, thanks!
